### ISSUE TITLE
NXEmptyView prevents refreshing with UIRefreshControl

### ISSUE THREAD

**Issue by robb** [nxtbgthng/UITableView-NXEmptyView#1]
When adding the empty view to a table view that also has an UIRefreshControl, the refresh control can no longer be accessed and pull-to-refresh is not working.

**Comment by stigi** [comment]
Thanks for reporting. I noticed the same issues with SVPullToRefresh.

**Comment by calimarkus** [comment]
Is it enough to set `userInteraction = NO` on the emptyView? Then everyone could choose on his own to use pull-to-refresh, or to have interaction on his own emptyview instead.

**Comment by stigi** [comment]
@jaydee3 not exactly.

The empty view is added as a subview atm. So, it won't scroll with pull to refresh.
One way could be to add it as a table view cell/header. Another one would be to place the empty view behind the pull to refresh view, not sure if this is feasible.

Right now the pull to refresh view is moving under the empty view, which looks uglyish.

**Comment by calimarkus** [comment]
We could use the contentOffset in layoutSubviews:.

emptyView.frame = CGRectOffset(self.bounds, 0, MAX(0,-self.contentOffset.y));
This will scroll the emptyView (only downwards). But userInteraction has still to be set to NO on the emptyView.

**Comment by stigi** [comment]
See 6b582c8
I'm closing the issue. If it should not be working for you send me a test that fails :)
